In [2]:
import pandas as pd

In [4]:
df = pd.read_csv("data_cleaned.csv")

In [6]:
df.head()

,ID,Name,Age,Value,Wage,Preferred_Foot,Weak_Foot,Trick_Skills,Work_Rate,Position,...,Penalties,Composure,Marking,StandingTackle,SlidingTackle,Work_Rate_A,Work_Rate_D,Position_cat,Basic_Player,Position_Stat
0,158023,L. Messi,31,110500000,565000,Left,4,4,Medium/ Medium,RF,...,75,96,33,28,26,Medium,Medium,1,1,91
1,20801,Cristiano Ronaldo,33,77000000,405000,Right,4,5,High/ Low,ST,...,85,95,28,31,23,High,Low,1,1,91
2,190871,Neymar Jr,26,118500000,290000,Right,5,5,High/ Medium,LW,...,81,94,27,24,33,High,Medium,1,1,88
3,192985,K. De Bruyne,27,102000000,355000,Right,5,4,High/ High,RCM,...,79,88,68,58,51,High,High,2,1,88
4,183277,E. Hazard,27,93000000,340000,Right,4,4,High/ Medium,LF,...,86,91,34,27,22,High,Medium,1,1,89

In [16]:
duplicateRowsDF = df[df.duplicated(['ID'])]

In [17]:
print(duplicateRowsDF)

Empty DataFrame
Columns: [ID, Name, Age, Value, Wage, Preferred_Foot, Weak_Foot, Trick_Skills, Work_Rate, Position, Jersey_Number, Contract_Valid_Until, Height, Weight, Striker, CentralMidfielder, SideMidfielder, WingBack, CenterBack, Crossing, Finishing, HeadingAccuracy, ShortPassing, Volleys, Dribbling, Curve, FreeKickAccuracy, LongPassing, BallControl, Acceleration, SprintSpeed, Agility, Reactions, ShotPower, Jumping, Stamina, Strength, LongShots, Aggression, Interceptions, Positioning, Vision, Penalties, Composure, Marking, StandingTackle, SlidingTackle, Work_Rate_A, Work_Rate_D, Position_cat, Basic_Player, Position_Stat]
Index: []

[0 rows x 52 columns]